//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public decimal IDPRODUCTO { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public decimal PRECIO { get; set; }
        public decimal STOCK { get; set; }
        public decimal STOCK_CRITICO { get; set; }
        public Nullable<decimal> TIPO_PRODUCTO_ID { get; set; }
        public Nullable<decimal> FAMILIA_PRODUCTO_ID { get; set; }
        public Nullable<decimal> MARCA_ID { get; set; }
        public Nullable<decimal> CODIGO_BARRA_ID { get; set; }
    
        public virtual CODIGO_BARRA CODIGO_BARRA { get; set; }
        public virtual FAMILIA_PRODUCTO FAMILIA_PRODUCTO { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual TIPO_PRODUCTO TIPO_PRODUCTO { get; set; }
    }
}
